# PCA Manual

In [1]:
# import modul
import pandas as pd
from numpy import linalg as LA
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets

In [2]:
# Import dan Split Data
iris = datasets.load_iris()
atribut = iris.data
label   = iris.target

# bagi dataset menjadi train set dan test set
X_train, X_test, y_train, y_test = train_test_split(atribut, label, test_size=0.2,random_state = 3)

# m : banyak data ; n = banyak fitur
m,n = [*(X_train.shape)]

In [3]:
# transpose data
data = np.transpose(X_train)
data.shape

(4, 120)

In [4]:
# Standarisasi Data
from scipy import stats

In [5]:
Z = stats.zscore(data,axis=1)

In [6]:
# Menentukan Korelasi dengan Kovarians
C = np.cov(Z)
C

array([[ 1.00840336, -0.11793396,  0.87772692,  0.80789493],
       [-0.11793396,  1.00840336, -0.42111957, -0.37347926],
       [ 0.87772692, -0.42111957,  1.00840336,  0.97201329],
       [ 0.80789493, -0.37347926,  0.97201329,  1.00840336]])

In [7]:
from numpy import linalg as LA
[eig,v_eig] = LA.eig(C)

In [8]:
eig

array([2.93066161, 0.92145988, 0.16308146, 0.01841049])

In [9]:
v_eig

array([[ 0.51959014, -0.37810748, -0.71836082,  0.26649305],
       [-0.26909402, -0.92341431,  0.25062703, -0.10991138],
       [ 0.58183733, -0.03557961,  0.14283809, -0.79987292],
       [ 0.5648715 , -0.0554512 ,  0.63304115,  0.52640693]])

In [10]:
sorted_eig = sorted(eig)
sorted_eig.reverse()
sorted_eig

[2.9306616113575217,
 0.9214598771076385,
 0.16308146290664402,
 0.01841049400635127]

In [11]:
for i in range(len(sorted_eig)):
    print((list(eig)).index(sorted_eig[i]))

0
1
2
3


In [12]:
sort = np.argsort(eig)[-n:][::-1]
sort

array([0, 1, 2, 3], dtype=int64)

In [13]:
sorted_eig[0]

2.9306616113575217

In [14]:
v_eig[:,0]

array([ 0.51959014, -0.26909402,  0.58183733,  0.5648715 ])

In [15]:
## 5.---------Variance and Cumulative Variance-----------------
#  Prealocating Space________________________________________
percen_var = np.zeros(n)
cum_var    = np.zeros(n)

total      = 0
for i in range(n):
    total         = total+eig[sort[i]]
    percen_var[i] = (eig[sort[i]]/np.sum(eig))*100
    cum_var[i]    = (total/np.sum(eig))*100

In [16]:
percen_var

array([72.65598578, 22.84452612,  4.04306127,  0.45642683])

In [17]:
cum_var

array([ 72.65598578,  95.5005119 ,  99.54357317, 100.        ])

In [18]:
var = list(iris.feature_names)
var

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [19]:
    
##6.----------Displaying Results----------------------------
print(" ----------------------------------------------------------")
print("      Variable        Eigen        % of     Cumulative % ")
print("        Name          Value      Variance   of Variance")
print(" ----------------------------------------------------------")
for i in range(n):
    print(" %8r %9.6f %10.6f %12.6f" %(var[sort[i]],eig[sort[i]],percen_var[i],cum_var[i]))
    

 ----------------------------------------------------------
      Variable        Eigen        % of     Cumulative % 
        Name          Value      Variance   of Variance
 ----------------------------------------------------------
 'sepal length (cm)'  2.930662  72.655986    72.655986
 'sepal width (cm)'  0.921460  22.844526    95.500512
 'petal length (cm)'  0.163081   4.043061    99.543573
 'petal width (cm)'  0.018410   0.456427   100.000000


## PCA by Modul SkLearn

In [20]:
# Standarisasi Data
import sklearn.preprocessing
X_train = sklearn.preprocessing.StandardScaler().fit_transform(X_train)

In [21]:
from sklearn.decomposition import PCA
# membuat objek PCA dengan 4 principal component
pca = PCA(n_components=4)
# mengaplikasikan PCA pada dataset
pca_attributes = pca.fit_transform(X_train)
# melihat variance dari setiap atribut
pca.explained_variance_ratio_

array([0.72655986, 0.22844526, 0.04043061, 0.00456427])

In [22]:
pca = PCA(n_components = 2)
X_train_pca = pca.fit_transform(X_train)
X_test_pca = pca.fit_transform(X_test)

In [23]:
from sklearn import tree
decision_tree = tree.DecisionTreeClassifier()
model_pertama = decision_tree.fit(X_train, y_train)
model_pertama.score(X_test, y_test)

0.3333333333333333

In [24]:
model2 = decision_tree.fit(X_train_pca, y_train)
model2.score(X_test_pca, y_test)

0.8666666666666667